services:
  web:
    build:
      context: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app        # mount your source code
      - /app/node_modules  # keep node_modules inside container
